  #nome do pipeline
  name: Teste de UnidadeNext.js
  #definindo como o pipeline vai ser disparado (nesse caso vai ser quando alguém tenta realizar o push no cód)
  on: 
    push:
    #aqui colocamos quais os ramos devem ser monitorados:
      branches: [main]

  jobs:
    teste-unidade: 
      runs-on: ubutu-lastest
      steps:
        #definindo uma ação para o steep. 
        - uses: action/checkout@v3
        #definindo o ambiente de trabalho
        - name: Usar Node 18.x
          uses: actions/setup-node@v3
          with:
            #garantindo que a versão do node seja a escolhida acima
            node-version: '18.x'
        #executando a rotina de verificação do cód enviado
        - name: Instalar dependencias
          run: npm install
        - name: Build
          run: npm rum build
        - name: Rodar testes de unidade com Jest
          run: npx test
